# -*- coding: utf-8 -*-
"""ci_sound.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132K_FoqKUxtyNJUqzSoPMuozBKGDsC9Y
"""

import numpy as np
import scipy.signal as sp
import scipy.io.wavfile as wavfile
import matplotlib.pyplot as plt

# Загрузка WAV-файла, возвращает частоту дискретизации и массив данных
sample_rate, sound = wavfile.read('/content/best.wav')

# Корректировка cutoff_frequencies для функции butter
nyquist_rate = 0.5 * sample_rate
cutoff_frequencies = np.linspace(100, 8000, num_channels + 1) / nyquist_rate

# Применение полосных фильтров
num_channels = 12  # Количество каналов имплантата
filter_order = 2
b, a = sp.butter(filter_order, cutoff_frequencies, btype='bandpass', output='ba')
filtered_sound = sp.filtfilt(b, a, sound, axis=0)

# Сохранение обработанного звука в WAV-файл
wavfile.write('processed_sound.wav', sample_rate, filtered_sound.astype(np.int16))

print("Обработанный звук сохранен в файл 'processed_sound.wav'")